/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package student_management;
import javax.swing.*;
import java.util.*;
import java.io.*;
import java.text.*;
/**
 *
 * @author TatendaC
 */
public class AddEmployee extends javax.swing.JFrame {
    
    ArrayList<Job> jobs;
    ArrayList<Employee> employees;
    DecimalFormat formatter;
    
    /**
     * Creates new form AddEmployee
     */
    public AddEmployee() {
        initComponents();
        
        formatter = new DecimalFormat("#,###.00");
        jobs = new ArrayList<Job>();
        employees = new ArrayList<Employee>();
        populateArrayList1();
        
        String [] jobsArray = new String[jobs.size()];
        
        for(int i=0 ; i < jobs.size(); i++){
            jobsArray[i] = jobs.get(i).getNameOfJob() + ", R" + formatter.format(jobs.get(i).getSalary());
            
        }
        
        
        
        jComboJobTitle.setModel(new javax.swing.DefaultComboBoxModel<>(jobsArray));

    }
    
    public void populateArrayList1(){
            try{
                FileInputStream file = new FileInputStream("Jobs.dat");
                ObjectInputStream inputFile = new ObjectInputStream(file);
                
                boolean endOfFile = false;
                
                while(!endOfFile){
                    try{
                        
                        jobs.add((Job) inputFile.readObject());
                    }
                    catch(EOFException e){
                        endOfFile = true;
                    }
                    catch(Exception f){
                        
                        JOptionPane.showMessageDialog(null, f.getMessage());

                    }
                       
                }
                inputFile.close();
            }
            catch(IOException e){
                JOptionPane.showMessageDialog(null, e.getMessage());
                
            }
            
            try{
                FileInputStream file2 = new FileInputStream("Employees.dat");
                ObjectInputStream inputFile2 = new ObjectInputStream(file2);
                
                boolean endOfFile2 = false;
                
                while(!endOfFile2){
                    try{
                        
                        employees.add((Employee) inputFile2.readObject());
                    }
                    catch(EOFException e){
                        endOfFile2 = true;
                    }
                    catch(Exception f){
                        
                        JOptionPane.showMessageDialog(null, f.getMessage());

                    }   
                }
                inputFile2.close();
            }
            catch(IOException e){
                JOptionPane.showMessageDialog(null, e.getMessage());
                
            }
        }
    /**   public void saveJobsToFile(){
      *      try{
      *     FileOutputStream file = new FileOutputStream("Job.dat");
       *     ObjectOutputStream outputFile = new ObjectOutputStream(file);
       *     
       *         for(int i = 0; i < jobs.size(); i++){
       *         }
                
                outputFile.close();
                JOptionPane.showMessageDialog(null,"");
                    
            }catch(){
                
            }
        }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtxtEmployeeName = new javax.swing.JTextField();
        jtxtEmployeeSurname = new javax.swing.JTextField();
        jtxtNameOfJob3 = new javax.swing.JTextField();
        jComboJobTitle = new javax.swing.JComboBox<>();
        jbtnSaveNewJob = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Create A New Job By Entering The Data Below");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Employee Name");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Employee Surname");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Job Title");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Staff Number");

        jtxtEmployeeName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtxtEmployeeName.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtEmployeeName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtEmployeeNameActionPerformed(evt);
            }
        });

        jtxtEmployeeSurname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtxtEmployeeSurname.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtEmployeeSurname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtEmployeeSurnameActionPerformed(evt);
            }
        });

        jtxtNameOfJob3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtxtNameOfJob3.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtNameOfJob3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtNameOfJob3ActionPerformed(evt);
            }
        });

        jComboJobTitle.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboJobTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboJobTitleActionPerformed(evt);
            }
        });

        jbtnSaveNewJob.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnSaveNewJob.setIcon(new javax.swing.ImageIcon(getClass().getResource("/student_management/save.png"))); // NOI18N
        jbtnSaveNewJob.setText("Save");
        jbtnSaveNewJob.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jbtnSaveNewJob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSaveNewJobActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(60, 60, 60)
                        .addComponent(jtxtEmployeeName, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(38, 38, 38)
                        .addComponent(jtxtEmployeeSurname, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(78, 78, 78)
                        .addComponent(jtxtNameOfJob3, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(113, 113, 113)
                        .addComponent(jComboJobTitle, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(155, 155, 155))
            .addGroup(layout.createSequentialGroup()
                .addGap(291, 291, 291)
                .addComponent(jbtnSaveNewJob)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel1)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtEmployeeName, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtxtEmployeeSurname, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel4)
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboJobTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtxtNameOfJob3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(jbtnSaveNewJob)
                .addContainerGap(79, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtEmployeeNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtEmployeeNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtEmployeeNameActionPerformed

    private void jtxtEmployeeSurnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtEmployeeSurnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtEmployeeSurnameActionPerformed

    private void jtxtNameOfJob3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtNameOfJob3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtNameOfJob3ActionPerformed

    private void jComboJobTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboJobTitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboJobTitleActionPerformed

    private void jbtnSaveNewJobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSaveNewJobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnSaveNewJobActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddEmployee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboJobTitle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton jbtnSaveNewJob;
    private javax.swing.JTextField jtxtEmployeeName;
    private javax.swing.JTextField jtxtEmployeeSurname;
    private javax.swing.JTextField jtxtNameOfJob3;
    // End of variables declaration//GEN-END:variables
}
