/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package student_management;
import javax.swing.*;
import java.util.*;
import java.io.*;
/**
 *
 * @author Dell
 */
public class AddNewJob extends javax.swing.JFrame {
    ArrayList<Job> jobs;
    /**
     * Creates new form AddNewJob
     */
    public AddNewJob() {
        initComponents();
        jobs = new ArrayList<Job>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtxtNameOfJob = new javax.swing.JTextField();
        jtxtSalaryOfJob = new javax.swing.JTextField();
        jbtnSave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Create A New Job By Entering The Data Below");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Salary for the Job");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Name of Job");

        jtxtNameOfJob.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtxtNameOfJob.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtNameOfJob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtNameOfJobActionPerformed(evt);
            }
        });

        jtxtSalaryOfJob.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtxtSalaryOfJob.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtSalaryOfJob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtSalaryOfJobActionPerformed(evt);
            }
        });

        jbtnSave.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/student_management/save.png"))); // NOI18N
        jbtnSave.setText("Save");
        jbtnSave.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jbtnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbtnSave)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jtxtNameOfJob)
                                .addComponent(jtxtSalaryOfJob)))))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel3)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jtxtNameOfJob, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addComponent(jtxtSalaryOfJob, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35)
                .addComponent(jbtnSave)
                .addGap(57, 57, 57))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtNameOfJobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtNameOfJobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtNameOfJobActionPerformed

    private void jtxtSalaryOfJobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtSalaryOfJobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtSalaryOfJobActionPerformed

    private void jbtnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSaveActionPerformed
       
        if(jtxtNameOfJob.getText().isEmpty() || jtxtSalaryOfJob.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Please enter all fields");
        }else{
            String name = jtxtNameOfJob.getText().trim();
            String salary = jtxtSalaryOfJob.getText().trim();
            
            Job job = new Job(Double.parseDouble(salary), name);
            
            jobs.add(job);
            
            saveJobsToFile();
        }  
        
    }//GEN-LAST:event_jbtnSaveActionPerformed

    public void populateArrayList(){
            try{
                FileInputStream file = new FileInputStream("Jobs.dat");
                ObjectInputStream inputFile = new ObjectInputStream(file);
                
                boolean endOfFile = false;
                
                while(!endOfFile){
                    try{
                        
                        jobs.add((Job) inputFile.readObject());
                    }
                    catch(EOFException e){
                        endOfFile = true;
                    }
                    catch(Exception f){
                        
                        JOptionPane.showMessageDialog(null, f.getMessage());

                    }
                     
                }
                inputFile.close();
            }
            catch(IOException e){
                JOptionPane.showMessageDialog(null, e.getMessage());
                
            }
        }
    
        public void saveJobsToFile(){
            
            try{
                FileOutputStream file = new FileOutputStream("Jobs.dat");
                ObjectOutputStream outputFile = new ObjectOutputStream(file);
                
                for(int i = 0; i < jobs.size(); i++){
                    outputFile.writeObject(jobs.get(i));
                    
                }
                    outputFile.close();
                    JOptionPane.showMessageDialog(null, "Job saved successfully");  
                    this.dispose(); 

                
            }catch(IOException e){
              JOptionPane.showMessageDialog(null, e.getMessage());  
                 
            }
            
        }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddNewJob.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddNewJob.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddNewJob.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddNewJob.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddNewJob().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton jbtnSave;
    private javax.swing.JTextField jtxtNameOfJob;
    private javax.swing.JTextField jtxtSalaryOfJob;
    // End of variables declaration//GEN-END:variables
}
